// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUW4apAZkSRoxc2nQnuJbIDRPkiKCOgfM',
    appId: '1:138626836508:android:5ff89f6c7bc5e0078e57d9',
    messagingSenderId: '138626836508',
    projectId: 'wechat-f535c',
    storageBucket: 'wechat-f535c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRuvK1ghGLzi15KF_WUpMbId9c5DSWeAY',
    appId: '1:138626836508:ios:20c12ae97ea5fb808e57d9',
    messagingSenderId: '138626836508',
    projectId: 'wechat-f535c',
    storageBucket: 'wechat-f535c.appspot.com',
    androidClientId: '138626836508-6nq1qkpf3kgr40snh6hba6lnvdn7lnpt.apps.googleusercontent.com',
    iosClientId: '138626836508-eccnbtmf91naikffhjr360bu8rcb1ugf.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
